stages:
  - build

makedeb:
  stage: build
  script:
    - docker build -t karafbuilder .
    - docker run --name karaf_build_$(date "+%s") -v $(pwd)/package:/build/package  karafbuilder
  artifacts:
    paths:
      - package/*.deb
